#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

for i in $DIR/../*.ipynb; do
    FNAME=$(basename "$i")
    echo running $FNAME

    if [ "$FNAME" != "04-NCDatasets-tutorial.jl" ]; then
       jupyter nbconvert --to html --execute --ExecutePreprocessor.timeout=600 "$i"
    fi
done

